@startuml SCP-UA Proxy
!pragma teoz true
skinparam style strictuml
hide footbox

participant "**SCU**" as SCU
box SCP / User Agent proxy
  participant "SCP" as SCP
  participant "User Agent" as UA
end box
participant "**Origin Server**" as OS

== Get Applicable //Workitems// ==
activate SCU

SCU -> SCP: A-ASSOCIATE-RQ( 1.2.840.1008.5.1.4.31 )
activate SCP
SCU <-- SCP: A-ASSOCIATE-AC
SCU -> SCP: C-FIND-RQ( 1.2.840.10008.5.1.4.31, ... )
note left: [PS3.4, K.4.1]\n<color:red>Query
SCP -> UA: perform Search request\nusing DIMSE parameters
activate UA
UA -> UA: convert DIMSE to\nDICOMweb parameters
UA -> OS: HTTP GET /workitems?{&match*}...
activate OS
note left: [PS3.18, 11.9]\nSearch
UA <-- OS: 200 (OK), //Workitems//
loop i: 1..#//Workitems//
  UA -> UA: convert //Workitem//<sub>i</sub>\nto DIMSE
  SCP <-- UA: return //Workitem//<sub>i</sub>
  SCU <-- SCP: C-FIND-RSP: FF00H (Pending), //Workitem//<sub>i</sub>
end
SCP <-- UA: ready
SCU <-- SCP: C-FIND-RSP: 0000H (Success)
SCU -> SCP: A-RELEASE-RQ
SCU <-- SCP: A-RELEASE-RSP
...

== Claim and Prepare //Workitem// ==
SCU -> SCP: A-ASSOCIATE-RQ( 1.2.840.10008.3.1.2.3.3 )
SCU <-- SCP: A-ASSOCIATE-AC
SCU -> SCP: N-CREATE-RQ( 1.2.840.10008.3.1.2.3.3,\nMPPSInstanceUID, ... )
note left: [PS3.4, F.7.2.1]\nCreate
SCP -> UA: perform Change State\nand Update requests\nusing DIMSE\nparameters
UA -> UA: convert DIMSE to\nDICOMweb parameters\nand payload
UA -> OS: HTTP GET /workitems?{&match}...
note left: <color:red>look for applicable\n<color:red>//Workitem// based on\n<color:red>DIMSE parameters
UA <-- OS: 200 (OK), //Workitem//
UA -> OS: HTTP PUT /workitems///Workitem///state\nTransactionUID, "IN PROGRESS"
note left: [PS3.18, 11.7]\nChange Workitem\nState
UA <-- OS: 200 (OK)
UA -> OS: HTTP POST /workitems///Workitem//?TransactionUID\n//Payload//
note left: [PS3.18, 11.6]\nUpdate Workitem
UA <-- OS: 200 (OK)
SCP <-- UA: ready
SCU <-- SCP: N-CREATE-RSP: 0000H (Success)
opt when not reusing the association
  SCU -> SCP: A-RELEASE-RQ
  SCU <-- SCP: A-RELEASE-RSP
end
...
== Report Progress on //Workitem// ==
loop until done, typically once
  SCU -> SCU: perform procedure step
  opt when not reusing the association
    SCU -> SCP: A-ASSOCIATE-RQ( 1.2.840.10008.3.1.2.3.3 )
    SCU <-- SCP: A-ASSOCIATE-AC
  end
  SCU -> SCP: N-SET-RQ( MPPSInstanceUID, \n//ProcedureStepInformation// )
  note left: [PS3.4, F.7.2.2]\nSet Information
  SCP -> UA: perform Update request\nusing DIMSE parameters
  UA -> UA: convert DIMSE to\nDICOMweb parameters\nand payload
  UA -> OS: HTTP POST /workitems///Workitem//?TransactionUID\n//Payload//
  note left: [PS3.18, 11.6]\nUpdate Workitem
  UA <-- OS: 200 (OK)
  SCP <-- UA: ready
  SCU <-- SCP: N-SET-RSP: 0000H (Success)
  opt when not reusing the association
    SCU -> SCP: A-RELEASE-RQ
    SCU <-- SCP: A-RELEASE-RSP
  end
end
...
== Change //Workitem// State<sub>Completed</sub> ==
opt when not reusing the association
  SCU -> SCP: A-ASSOCIATE-RQ( 1.2.840.10008.3.1.2.3.3 )
  SCU <-- SCP: A-ASSOCIATE-AC
end
SCU -> SCP: N-SET-RQ( MPPSInstanceUID, Completed )
note left: [PS3.4, F.7.2.2]\nSet Information
SCP -> UA: perform Change State\nrequest using DIMSE\nparameters
UA -> OS: HTTP PUT /workitems///Workitem//\nTransactionUID, "COMPLETED"
note left: [PS3.18, 11.7]\nChange Workitem\nState
UA <-- OS: 200 (OK)
deactivate OS
SCP <-- UA: ready
deactivate UA
SCU <-- SCP: N-SET-RSP: 0000H (Success)
SCU -> SCP: A-RELEASE-RQ
SCU <-- SCP: A-RELEASE-RSP
deactivate SCP
deactivate SCU