@startuml SCP-UA Proxy
!pragma teoz true
skinparam style strictuml
hide footbox

participant "User Agent" as UA
box Origin Server / SCU proxy
  participant "**Origin Server**" as OS
  participant "**SCU**" as SCU
end box
participant "SCP" as SCP
actor User

== Subscribe ==
activate UA
opt when there is no notification connection yet
  UA -> OS: GET \\n Host: host \\n Upgrade: "WebSocket" ...
  activate OS
  note left: [PS3.18, 8.10.4]\nOpen Notification\nConnection
  UA <-- OS: 101 (Switching Protocols)
end
UA -> OS: POST SP /workitems/{resource}/\nsubscribers/{aetitle}...
note left: [PS3.18, 11.10]\nSubscribe


'Add a loop where SCU polls the SCP using N-GET'
== Polling ==
activate SCU
OS -> SCU: poll for\nworkitem changes
'Open association for N-GET'
SCU -> SCP: A-ASSOCIATE-RQ( AE title,\n1.2.840.10008.
SCP --> SCU: A-ASSOCIATE-AC
loop Polling for changes
SCU -> SCP: N-GET(\\nSOPInstanceUID, AttributeList )
SCP --> SCU: N-GET-RSP(\\nSOPInstanceUID, AttributeList )
SCU -> SCU: convert AttributeList to workitem
OS <-- SCU: workitem
UA //-- OS: [websocket<sub>AE Title</sub>] //send event report//(\nSOPInstanceUID, EventType )
note right: [PS3.18, 8.10.5]\nSend Event Report
end

'Unsubscribe for the polling'
UA -> OS: POST SP /workitems/{resource}/\nsubscribers/{aetitle}...
note left: [PS3.18, 11.11]\nUnsubscribe
OS -> SCU : stop loop and close association
SCU -> SCP: A-RELEASE-RQ
SCP --> SCU: A-RELEASE-RSP
deactivate SCU
deactivate OS
deactivate UA
@enduml