@startuml OS-SCU Proxy
!pragma teoz true
skinparam style strictuml
hide footbox

participant "User Agent" as UA #a2c777
box Origin Server / SCU proxy #d9e8c8
  participant "**Origin Server**" as OS #a2c777
  participant "**SCU**" as SCU #a2c777
end box
participant "SCP" as SCP #a2c777

activate UA
UA -> UA: perform procedure step
UA -> OS: HTTP PATCH /modality-performed-\nprocedure-steps///MPPS-UID//\n//payload//
activate OS
note left #ecf4e4: [PS3.18, X.5]\nUpdate
OS -> OS: convert DICOMweb payload\nand parameters to DIMSE\nparameters
OS -> SCU: perform Update request\nusing DIMSE parameters
activate SCU
SCU -> SCP: A-ASSOCIATE-RQ( 1.2.840.10008.3.1.2.3.3 )
activate SCP
SCU <-- SCP: A-ASSOCIATE-AC
SCU -> SCP: N-SET-RQ( //MPPS-UID//, //Modality Performed//\n//Procedure Step Information// )
note left #ecf4e4: [PS3.4, F.7.2.2]\nSet Information
SCU <-- SCP: N-SET-RSP: 0000H (Success)
SCU -> SCP: A-RELEASE-RQ
SCU <-- SCP: A-RELEASE-RSP
deactivate SCP
OS <-- SCU: OK
deactivate SCU
UA <-- OS: 200 (OK)
deactivate OS
@enduml